# Generated by Django 5.2 on 2025-05-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Футболист',
                'verbose_name_plural': 'Состав команды',
            },
        ),
    ]
