# Generated by Django 5.2 on 2025-05-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='player_photo/%y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='team.position', verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
