# Generated by Django 5.2 on 2025-05-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_player_birth_date_player_height_player_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, verbose_name='Национальность'),
        ),
    ]
