# Generated by Django 5.2 on 2025-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='team_photo/%y/%m/%d', verbose_name='Лого'),
        ),
    ]
