# Generated by Django 5.2 on 2025-05-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='time_update',
        ),
    ]
