# Generated by Django 5.2 on 2025-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_news_options_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_photos/%y/%m/%d', verbose_name='Фото'),
        ),
    ]
