# Generated by Django 5.2 on 2025-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_photo/%y/%m/%d', verbose_name='Фото'),
        ),
    ]
